flavray/avro-rs

benches/serde.rs
benches/single.rs
examples/benchmark.rs
src/codec.rs
src/de.rs
src/encode.rs
src/lib.rs
src/reader.rs
src/types.rs
src/writer.rs

This PR is proposing some changes to the writer module (and partially to the whole crate) as per the following commit messages.
```
Make encode and decode private
There is little reason why these should be public, especially if we
expose a write function with very little overhead.
They can always be made public when needed.
```
---
```
Substitute SingleWriter with to_avro_datum
The avro implementations in other languages provide a DataFileWriter and
a DatumWriter which are respectively the interface to write to a file
with buffering and headers and the interface to just convert a value to
avro.
While Writer is definitely equivalent (actually more generic than
DataFileWriter since it accepts anything implementing Write), the
SingleWriter struct wasn't really similar to DatumWriter. For …
```

Writer module overhauling

---

benches/serde.rs
examples/benchmark.rs
src/decode.rs
src/encode.rs
src/lib.rs
src/reader.rs

```
Add documentation for reader module
```
---
```
Re-export Reader in lib.rs
```
---
```
Add tests for Reader and read header at creation
Implementing a lazy reading of the header causes a couple problems in
the implementation (e.g. infinite loops without a couple state flags)
and the writer schema to be an Option until the first value is read
or read_header is called. For this reason, header is read at creation
time and now both new and with_codec do return a Result.
Writing tests, a second bug that could cause many errors to be returned
by the iterator instead of only one emerged. To fix it, a flag to signal
that the reader entered in a state of error has been added, so the
iteration will stop automatically at the next step.
```
---
```
Add from_avro_datum function and more tests for …
```

Reader module tests, documentation and interface overhaul

---

src/decode.rs
src/schema.rs
src/types.rs

Also features a small refactor of `Schema::Record`
Closes #8 
(This PR ended being quite long, sorry and thanks in advance 🙈 )
---
```
Remove RecordSchema struct
This makes `Schema::Record` more in line with the other `Schema::`
variants (`Enum` and `Fixed`).
Also makes creation of `Schema::Record` easier (less `Rc`, one less
struct) and allows to use only specific items (e.g: `fields`).
```
---
```
Add documentation and tests to Schema
```
---
```
Avoid borrowing Schema in types::Record
```
---
```
Add documentation for Record
```
---
```
Add module-level documentation for schema.rs and types.rs
```
---
```
Add docstrings for parse_*
```

Schema documentation and unit tests.

---

src/encode.rs
src/writer.rs

I had to make `encode` take a Schema as parameter to help "guide" the encoding. Quite unhappy about it, but that's the least-worst I could come up with.
Adding a `Schema` to `ToAvro` would have added too much overhead for complex types (having to rebuild an array, map or record everytime `.avro()` is called).

Avoid calling .resolve when writing datum

---

src/de.rs
src/lib.rs
src/writer.rs

Fixes #25 
Add missing asterisks in documentation.
---
Fix Writer::extend documentation.
Writer::extend makes an internal call to `flush`. Even if we rely on
the internal buffering while appending each of the values from the
iterator, data is actually written to the inner `io::Write` interface in
the end. Made this explicit.
---
Make from_avro_datum publicly available.
Because to_avro_datum is public, and it makes sense to have this
one public as well, in case anyone needs it.
---
Add documentation for from_value.
Documentation was missing for this "key" function. Took the liberty
to re-use the words from serde_json as the wording is nice 🙂
(https://docs.serde.rs/serde_json/fn.from_value.html)

Various fixes/improvements to the documentation

---

Cargo.toml
src/codec.rs
src/decode.rs
src/lib.rs
src/reader.rs
src/schema.rs
src/types.rs
src/util.rs
src/writer.rs

This change moves the crate from using strings as errors, which is a
pattern that should be used only for prototyping, to defining custom
fail types, based on https://boats.gitlab.io/failure/
I have decided to define four different error structs based on what is
written in this GitHub issue:
https://github.com/rust-lang-nursery/failure/issues/7
However, I am very open to change everything to a single error type
defined as an enum, if you prefer so.
In addition, this branch also resurrects a simple zigzag test that
slipped through our test revamp as commented.

Move from string as errors to custom fail types

---

src/reader.rs

Fixes #31 
The current implementation creates a new view of `bytes` for each
iteration, meaning it is forced to read the first item in `bytes` over
and over, due to a [gotcha](https://doc.rust-lang.org/src/std/io/impls.rs.html#180) in the `io::Read` implementation of `&'a [u8]`.
The new implementation will consume bytes after each call to
`from_avro_datum`, effectively reading all the items.
Also, change the reader unit-test to make it test this case.

Use a single &[u8] when decoding items in Reader

---

src/decode.rs
src/encode.rs
src/reader.rs
src/writer.rs

Previously the index at the beginning of an union value
had been a directly-encoded byte.  Also fixes a problem where
the value was not correctly wrapped in a Value::Union upon decode.
Also, tests for all new code.
Fixes #33.

Encodes/decodes union values with a leading zig-zag long.

---

src/schema.rs

I needed the `namespace` field implemented, but figured I'd add in `doc` and `aliases` while I was at it.

Added some missing serialization fields for the `Schema::Record` variant.

---

README.md
examples/benchmark.rs
src/de.rs
src/decode.rs
src/lib.rs
src/reader.rs
src/schema.rs
src/types.rs
src/util.rs

Fixes #40
Upon bogus input data, decoding could allocate an insane amount of
memory (if length field is misencoded to a huge number) and panic.
To avoid this behaviour, this change introduces a limit (default 512MB)
to any allocation that can be done when decoding data.
Also return errors when decoding bogus int/long causing overflows.
Benchmark don't seem impacted by the change
```
New
running 14 tests
test bench_big_schema_read_100000_record   ... bench: 122,871,823 ns/iter (+/- 9,714,148)
test bench_big_schema_read_10000_record    ... bench:  12,737,304 ns/iter (+/- 2,848,853)
test bench_big_schema_read_100_record      ... bench:     134,765 ns/iter (+/- 19,624)
test bench_big_schema_read_1_record        ... bench:      16,293 ns/iter (+/- 7,916)
test …
```

Add a maximum allocation size when decoding

---

CHANGELOG.md
examples/to_value.rs
src/lib.rs
src/ser.rs

Reciprocal function of `from_value`.
Fixes #45

Add `to_value` to the API

---

Cargo.toml
README.md
src/lib.rs
src/schema.rs

Added SHA-256 and MD5 but haven't added Rabin due to lack of a well supported library. May
be implemented at a later phase either directly here or by creating a library to calculate
it.

Add fingerprinting generation to library

---

Cargo.toml

Commit 35d2108 converted many source files to use Rust 2018
features (e.g., `use crate`).  These changes make avro-rs impossible
to build with older versions of the compiler.
~/src/avro-rs$ rustc --version
rustc 1.29.2 (17a9dc751 2018-10-05)
~/src/avro-rs$ cargo check
Checking avro-rs v0.6.4 (file:///home/vincent.foley/src/avro-rs)
error[E0658]: `crate` in paths is experimental (see issue #45477)
--> src/codec.rs:12:5
|
12 | use crate::types::{ToAvro, Value};
|     ^^^^^
error[E0658]: `crate` in paths is experimental (see issue #45477)
--> src/codec.rs:13:5
|
13 | use crate::util::DecodeError;
|     ^^^^^
[Many more errors]
error: aborting due to 33 previous errors
For more information about this error, try `rustc --explain E0658`.
error: Could not compile `avro-rs`.
To learn more, run …

Add edition declaration to Cargo.toml

---

.pre-commit-config.yaml
.requirements-precommit.txt
.rustfmt.toml
.travis.yml
Cargo.toml
Makefile
README.md
benches/serde.rs
benches/serde_json.rs
benches/single.rs
examples/benchmark.rs
examples/to_value.rs
src/codec.rs
src/de.rs
src/decode.rs
src/encode.rs
src/lib.rs
src/reader.rs
src/schema.rs
src/ser.rs
src/types.rs
src/util.rs
src/writer.rs
tests/resolve.rs
tests/validate.rs

- Install rustfmt and clippy on stable
- Drop rustfmt option only available in nightly
- Remove all unecessary extern crate and macro use
- Update serde and failure crate usage of macros
- Optimize some imports
- Bump dependencies
- Also minor adjustments to Makefile

Make use of rust 2018 features

---

src/reader.rs
src/schema.rs
tests/io.rs
tests/schema.rs

```
Port tests from apache/avro test_schema.py and implement schema equality based on parsing canonical form
I noticed that we were deriving PartialEq for Schema while my understanding
is that the spec asserts that equality between schemas has to rely on
parsing canonical form. So I manually impemented PartialEq and Eq based
on that.
I also created a bunch of issues to follow with the tests that I had to
comment because they were failing.
```
Closes #18

Port tests from apache/avro test_schema.py and implement schema equality based on parsing canonical form

---

src/de.rs
src/lib.rs
src/ser.rs

This is useful for people who use the error handling strategy of
defining wrapper Errors around the different kinds of errors that may be
expected. Without making the Error types encountered public it's not
possible to create new error types that wrap them.
I re-exported the errors renamed, as I'm guessing by current code
organization you don't want the de and ser modules public, though that
could just as well be done just making everything non-public as
`pub(crate)`.

Re-export {de,ser}::Error

---

src/types.rs
tests/io.rs

See comments in #96 for more info.
I am a bit scared of the performance implications in case of many
union fields with default value null to allow backward compatibility, so
I added an explicit branch in the default resolution to handle null
without a couple more allocations.
The most efficient solution would be to precompute the default value as
part of the schema parsing and store it as the default for the field
instead of its JSON representation, as we are instead doing now.

Fix union resolution

---

src/decode.rs
src/encode.rs

`avro-rs` currently doesn't conform to the binary encoding spec for `f32` and `f64` values which states:
```
* a float is written as 4 bytes. The float is converted into a 32-bit integer using a method equivalent to Java's floatToIntBits and then encoded in little-endian format.
* a double is written as 8 bytes. The double is converted into a 64-bit integer using a method equivalent to Java's doubleToLongBits and then encoded in little-endian format.
```
This PR fixes that.
ref: https://avro.apache.org/docs/1.8.1/spec.html#binary_encode_primitive

Fix f32 and f64 encoding/decoding

---

Cargo.toml
src/writer.rs

This PR makes block size configurable in `Writer`.
The approach uses the [`typed_builder`]() crate to enable this feature.
After this PR you can call the `block_size` method to construct a new `writer`
using `typed_builder`:
```rust
let mut writer = Writer::builder().block_size(100).writer(writer).schema(&schema).build();
```
Without calling the `block_size` method the default value of `16000` is used.

Make writer block size configurable

---

Cargo.toml
benches/serde.rs
benches/serde_json.rs
benches/single.rs
scripts/travis-test.sh

This PR ports micro benchmarks to criterion.
Criterion works on stable, and is actively maintained and developed.
It also provides much more useful benchmarking data than libtest does.
Finally, it keeps track of the last run and gives useful output indicating possible regressions.

Port benchmarks to criterion

---

src/schema.rs
src/writer.rs

This PR adds a test for writing a nullable logical type.
Nullable logical types are specified using union of `null`, and the logical type:
```
{"type": ["null", {"type": "long", "logicalType": "timestamp-micros"}]}
```
Closes #122.

Add a test for nullable logical types

---

Cargo.toml
Makefile
README.md
README.tpl
src/lib.rs

By bringing in `cargo-readme` the canonical source for README.md documentation
will be the library documentation, also shown in docs.rs.
This commit moves some documentation only in the README into `src/lib.rs` and
therefore docs.rs also gets a good update.
The downside to this is that there's yet another tool being depended upon and a
new template file `README.tpl`. All in all a minor downside I think.

Generate README.md with `cargo-readme`

---

README.md
src/lib.rs
src/schema.rs
src/schema_compatibility.rs

Most of this was transplanted from
https://github.com/apache/avro/blob/master/lang/ruby/lib/avro/schema_compatibility.rb as a
proof of concept.
What that means is that I'd be keen on early feedback on all things here, so that we can
get a good way to check for schema compatibility in this library, without me committing
too much (in terms of design) up front.

Add schema compatibility to library

---

README.md
benches/serde.rs
examples/benchmark.rs
src/lib.rs
src/schema_compatibility.rs
src/writer.rs

This is in line with other buffer implementations out there, like
https://doc.rust-lang.org/std/io/struct.BufWriter.html#method.into_inner

Make writer.into_inner() call flush() and return a Result

---

Cargo.toml
src/schema.rs

This also includes a bump for sha2 library. As it stands, the trait changed,
meaning this will actually be a breaking change for anyone using the fingerprint
functionality of `avro-rs`.

Bump digest library to 0.9 and its dependencies

---

benches/serde.rs
benches/single.rs
examples/benchmark.rs
src/codec.rs
src/reader.rs
src/ser.rs
src/types.rs
src/writer.rs

This PR deprecates the `ToAvro` trait in favor of `From<T> for Value` implementations.
`ToAvro` is now implemented in terms of `From`, along with a deprecation warning to any code that uses it from the next release onward.

Deprecate ToAvro in favor of From<T> for Value impls

---

src/codec.rs
src/schema.rs

This PR replaces some manual `from_str` implementations with a derive of `strum_macros::EnumString`.

Replace some manual from_str impls with strum

---

.pre-commit-config.yaml
CHANGELOG.md
Cargo.toml
README.md
README.tpl
examples/to_value.rs
migration_guide.md
src/codec.rs
src/de.rs
src/decimal.rs
src/decode.rs
src/errors.rs
src/lib.rs
src/reader.rs
src/schema.rs
src/ser.rs
src/types.rs
src/util.rs
src/writer.rs
tests/io.rs
tests/schema.rs

Closes #115
This is still a WIP branch, with lots of TODOs and some things about
thiserror I still can't wrap my head around. However, the heavy-lifting
is done, the failure crate has been removed from the list of
dependencies and compilation, tests, benchmarks and linting are all
green.
The two biggest things I have yet to figure out are:
1. How to deal with the errors manually defined in ser.rs and de.rs:
they are publicly available and as soon as I touch anything I hit
cryptic serde errors
2. How to make errors like TryFromIntError part of more abstract ones
like ParseSchemaError, which could have a source error or just a
String description.

Move from failure to thiserror

---

benches/serde.rs
benches/serde_json.rs
benches/single.rs
examples/benchmark.rs
rustfmt.toml
src/codec.rs
src/de.rs
src/decode.rs
src/encode.rs
src/lib.rs
src/reader.rs
src/schema.rs
src/schema_compatibility.rs
src/ser.rs
src/types.rs
src/util.rs
src/writer.rs
tests/io.rs
tests/schema.rs

This PR adds `rustfmt.toml` with two settings (and applies the config to the repo):
- `edition = "2018"` -- this is needed for running `rustfmt` on language features that are 2018 only, such as `async`/`await`
while we don't have any `async`/`await` specifically, `avro-rs` _is_ a 2018 edition crate so we should have a rustfmt.toml consistent with that
- `merge_imports = true` -- this is a style preference

Add rustfmt.toml and consolidate imports

---

CHANGELOG.md
src/schema.rs
tests/schema.rs

This PR adds handling for logical types in canonical form schemas which allows
uncommenting the logical type tests in `tests/schema.rs` except for decimal.
There's a bug in the `fixed`-type decimal schema parsing, a PR is coming for that shortly.

Handle logical types in canonical form schema

---

Cargo.toml

By update [rand](https://crates.io/crates/rand) crate this PR fix advisory [RUSTSEC-2019-0035](https://rustsec.org/advisories/RUSTSEC-2019-0035).
Before:
```
$ cargo-deny check advisories
2020-12-16 20:20:41 [WARN] unable to find a config path, falling back to default config
warning[A004]: Unaligned memory access
┌─ /home/kirill/projects/avro-rs/Cargo.lock:59:1
│
59 │ rand_core 0.3.1 registry+https://github.com/rust-lang/crates.io-index
│ --------------------------------------------------------------------- unsound advisory detected
│
= ID: RUSTSEC-2019-0035
= Advisory: https://rustsec.org/advisories/RUSTSEC-2019-0035
= Affected versions of this crate violated alignment when casting byte slices to
integer slices, resulting in undefined behavior.
The flaw was corrected by Ralf Jung and …
```

Bump rand crate to 0.7.0

---

src/types.rs

With the upgrade to Rust 1.49, the clippy lint `unnecessary_cast` was
[enhanced to work with integer and float literals][0]. There is one
instance of this in the code base that is breaking the build.
This change removes the cast and fixes the clippy warning.
[0]: https://github.com/rust-lang/rust-clippy/blob/00586dfdcd10c37cb8b132c72ed0558304955042/CHANGELOG.md#enhancements-1

Remove unnecessary cast (clippy warning)

---

Cargo.toml
src/error.rs
src/schema.rs

Ensure that symbol names are valid ([A-Za-z_][A-Za-z0-9_]*) and unique
within an enum.
Fixes #179

Validate enum symbols
