src/codec.rs
src/de.rs
src/lib.rs
src/ser.rs

* Make private modules that don't need to be public: specifically ser, de and codec.
* Add documentation and tests for the codec module

Add docs and tests to codec module and make private modules that don't need to be public

---

src/de.rs
src/decode.rs
src/encode.rs
src/lib.rs
src/reader.rs
src/ser.rs
src/types.rs
src/writer.rs

Full support for Enum; closes #5; closes #6 
Also make the reader's iterator return a result of Value so to able to communicate errors

Full Enum support and reader's iterator returns Result

---

README.md
src/lib.rs
src/schema.rs

```
Add badges and info to README
```
---
```
Make example main() return Result so we can use ?
```
---
```
Write home page tutorial
Also re-export Reader at the top level of the library
```
---
To test it I recommend checking the branch locally and run `make doc-local`.
You'll also need to add your repo to badge.fury.io to make the version badge work.
Close #11 
Close #12

Write tutorial and README

---

README.md

Use crates.io badge

---

benches/serde_json.rs
src/codec.rs
src/de.rs
src/decode.rs
src/encode.rs
src/reader.rs
src/schema.rs
src/ser.rs
src/types.rs
src/util.rs
src/writer.rs

```
Run make lint
```
---
``` 
Implement changes suggested by clippy
```
And that's it. Performance don't seem impacted (maybe got a tiny bit faster?): https://pastebin.com/BWBsk1F0

Linting and clipping

---

.pre-commit-config.yaml
Makefile

Run clippy as pre-commit

---

CHANGELOG.md
Cargo.toml
src/codec.rs
src/lib.rs

Fix snappy codec

---

src/util.rs

`util::encode_variable(i64)` took a i64 but used both `>>` (which does an arithmetic shift for i64) and `>=`. Those operations don't work on numbers/bytes which are still zig-zag-encoded because a large zig-zag
encoded number may have a leading `1`. This breaks `>=` as the number is assumed to be negative and also the right-shift will keep introducing new `1`s which leads to an infinite loop.
Replacing the argument (and the callsites) with an u64 fixes those issues.
To make sure this does not regress in the future, tests for `i64::MAX` and `i64::MIN` have been added.

Fix variable-length encoding for big i64 numbers

---

src/decode.rs

Negative block lengths are not handled

---

src/decode.rs
tests/io.rs

Uncomment enum default test and remove unused test import

---

src/de.rs
src/ser.rs
src/util.rs

This PR fixes a number of warnings seen on `master`.

Fix warnings on master

---

src/decode.rs
src/encode.rs
src/reader.rs

This PR removes a number of unsafe that calls that appear to be unnecessary.

Remove some unsafe

---

src/codec.rs
src/reader.rs

This PR fixes a bug where decompression would attempt to read `n` bytes, where
`n` is the length of the reader's buffer. If `n` is greater than the number of
bytes in a block then garbage will be decompressed and fail with a cryptic
error message.
This wasn't reproducible 100% of the time, likely due to memory allocation not
being reproducible across invocations of a program. That is, sometimes the
buffer's length will be equal to the number of bytes in a block, other times it
will be larger. I therefore did not add a test, as it would've been flakey.
If desired, I can spend some more time trying to come up with a test.
This PR is meant to address the bug until a better solution can be introduced.
Part of the issue is the `Codec` methods taking a `&mut Vec<u8>`. Since those methods
are …

Fix reader buffer length bug

---

src/decode.rs

Fix length casting during decoding

---

Cargo.toml

Update libflate to version 1.0

---

Cargo.toml
src/de.rs

This PR covers an issue previously opened by me, i.e. `Uuid` deserialization.

Implement deserialize for Uuid

---

CHANGELOG.md
Cargo.toml
README.md
src/lib.rs
src/rabin.rs
src/schema.rs

This adds Rabin fingerprinting via Digest.
I haven't done too much rust, so let me know if anything needs changing.

Implement the Rabin fingerprint algorithm

---

src/rabin.rs
src/schema.rs

Strip more fields in PCF

---

src/schema.rs
src/types.rs

Allow resolution of union schemas with logical types

---

src/types.rs

This is necessary for resolving maps as records in unions.

Validate maps as records
